services:
  db:
    image: postgres
    container_name: jittarakesh_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest-ecommerceDB
    ports:
      - '5434:5433'
    volumes:
      - '/Users/Siam/Documents/Projects/nest-ecommerce/db_data:/var/lib/postgresql/data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
